name = "FeynRuleParticle"
uuid = "86934286-9c20-4b5e-821d-811e56884bc4"
authors = ["Zejian Zhuang zejian.zhuang@uv.es"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
